name: Update on the mc.imcodist.xyz server.

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  update_server:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into main server and update repo.
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd resources/
            git pull
      - name: RCON into MC server and send reload request.
        uses: wolfigster/rcon-action@v1.0.2
        with:
          server: ${{ secrets.MC_RCON_SERVER }}
          port: ${{ secrets.MC_RCON_PORT }}
          password: ${{ secrets.MC_RCON_PASS }}
          commands: '["cdstreloadresources"]'
